@startuml Pipeline_Abstract

start
partition "Read Dirty Data" {
    :read list and matrix files;
}
partition "Cleaning Pipeline" {
    :clean up;
}
partition "Save Cleaned Data" {
    :save matrix file;
}
stop

@enduml